[build]
  command = "npm run build"
  publish = "dist"

[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 8080

[functions]
  directory = "netlify/functions"

[context.production.environment]
  NODE_ENV = "production"
